export const people = [
  {
    id: "1",
    name: "rishi",
    type: "AWS",
    app_ID: "a01",
    client_ID: "001",
    secret: "hidden_value",
    action: "view",
  },
  {
    id: "2",
    name: "bala",
    type: "S3",
    app_ID: "a02",
    client_ID: "002",
    secret: "hidden_value",
    action: "view",
  },
  {
    id: "3",
    name: "ram",
    type: "Azure",
    app_ID: "a03",
    client_ID: "003",
    secret: "hidden_value",
    action: "view",
  },
  {
    id: "4",
    name: "arun",
    type: "Google",
    app_ID: "a04",
    client_ID: "004",
    secret: "hidden_value",
    action: "view",
  },
  {
    id: "5",
    name: "priya",
    type: "AWS",
    app_ID: "a05",
    client_ID: "005",
    secret: "hidden_value",
    action: "view",
  },
  {
    id: "6",
    name: "kumar",
    type: "Azure",
    app_ID: "a06",
    client_ID: "006",
    secret: "hidden_value",
    action: "view",
  },
  {
    id: "7",
    name: "neha",
    type: "Google",
    app_ID: "a07",
    client_ID: "007",
    secret: "hidden_value",
    action: "view",
  },
  {
    id: "8",
    name: "suresh",
    type: "S3",
    app_ID: "a08",
    client_ID: "008",
    secret: "hidden_value",
    action: "view",
  },
  {
    id: "9",
    name: "rajesh",
    type: "AWS",
    app_ID: "a09",
    client_ID: "009",
    secret: "hidden_value",
    action: "view",
  },
  {
    id: "10",
    name: "jaya",
    type: "Azure",
    app_ID: "a10",
    client_ID: "010",
    secret: "hidden_value",
    action: "view",
  },
  // Add actions consistently for remaining objects...
];

export type Person = (typeof people)[number];
