export const people = [
  {
    name: "rishi",
    type: "AWS",
    app_ID: "a01",
    client_ID: "001",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "bala",
    type: "S3",
    app_ID: "a02",
    client_ID: "002",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "ram",
    type: "Azure",
    app_ID: "a03",
    client_ID: "003",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "arun",
    type: "Google",
    app_ID: "a04",
    client_ID: "004",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "priya",
    type: "AWS",
    app_ID: "a05",
    client_ID: "005",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "kumar",
    type: "Azure",
    app_ID: "a06",
    client_ID: "006",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "neha",
    type: "Google",
    app_ID: "a07",
    client_ID: "007",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "suresh",
    type: "S3",
    app_ID: "a08",
    client_ID: "008",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "rajesh",
    type: "AWS",
    app_ID: "a09",
    client_ID: "009",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "jaya",
    type: "Azure",
    app_ID: "a10",
    client_ID: "010",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "vikram",
    type: "AWS",
    app_ID: "a11",
    client_ID: "011",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "anu",
    type: "Google",
    app_ID: "a12",
    client_ID: "012",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "tarun",
    type: "S3",
    app_ID: "a13",
    client_ID: "013",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "meera",
    type: "Azure",
    app_ID: "a14",
    client_ID: "014",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "vijay",
    type: "AWS",
    app_ID: "a15",
    client_ID: "015",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "sahana",
    type: "Google",
    app_ID: "a16",
    client_ID: "016",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "raj",
    type: "S3",
    app_ID: "a17",
    client_ID: "017",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "geetha",
    type: "Azure",
    app_ID: "a18",
    client_ID: "018",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "deepak",
    type: "AWS",
    app_ID: "a19",
    client_ID: "019",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "shilpa",
    type: "Google",
    app_ID: "a20",
    client_ID: "020",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "arvind",
    type: "S3",
    app_ID: "a21",
    client_ID: "021",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "sneha",
    type: "Azure",
    app_ID: "a22",
    client_ID: "022",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "ajay",
    type: "AWS",
    app_ID: "a23",
    client_ID: "023",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "anita",
    type: "Google",
    app_ID: "a24",
    client_ID: "024",
    secret: "hidden_value",
    action: "view",
  },
  {
    name: "varun",
    type: "S3",
    app_ID: "a25",
    client_ID: "025",
    secret: "hidden_value",
    action: "view",
  },
];

export type Person = (typeof people)[number];
